plugins {
    id 'java'
    id 'org.springframework.boot' version '4.0.1'
    id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.example'
version = '0.0.1-SNAPSHOT'
description = 'LinkedInPuzzleSolvers'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-webmvc'
    implementation 'org.jsoup:jsoup:1.22.1'
    implementation 'org.seleniumhq.selenium:selenium-java:4.29.0'
    implementation 'software.amazon.awssdk:cloudwatch:2.30.5'
    implementation 'software.amazon.awssdk:s3:2.30.5'
    implementation 'org.jcodec:jcodec-javase:0.2.5'
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
    testImplementation 'org.springframework.boot:spring-boot-starter-webmvc-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

sourceSets {
    test {
        java {
            srcDirs = ['tst/java']
        }
        resources {
            srcDirs = ['tst/resources']
        }
    }
}

springBoot {
    mainClass = 'com.LambdaHandler'
}

tasks.named('test') {
    useJUnitPlatform()
}
